### ISSUE TITLE
Support Maximum timeout for a magnet & Handle/Ignore the exception on bulk magnets

### ISSUE THREAD

**Issue by mhdzumair** [jwodder/demagnetize#23]
Hi @jwodder. Thanks for the wonderful implementation. I had an implementation to find the torrent information from magnet. i have used your library to implement that. It's working perfectly however for my custom requirement. I just only want to get the torrent information rather than creating torrent files. So I made custom changes to be able to work. 

Implementation usage: https://github.com/mhdzumair/MediaFusion/blob/develop/utils/torrent.py#L92-L150

I would like to request for creating functions to use this as library which can be used for other project rather than only focusing cli usage.

**Comment by jwodder** [comment]
@mhdzumair The title of this issue seems to be asking for something completely different from the body.  If you just want to be able to use `demagnetize` as a library, then the title of the issue should say so.  If you also want maximum timeouts for getting magnet info and "handle/ignore the exception on bulk magnets" (not sure what that's supposed to mean), then create separate issues for each of those feature requests.

**Comment by mhdzumair** [comment]
yes it might be into separate, but to ask is to have a function to get metadata and also support the maximum timeout and handle exception. So that failing torrent won't stop in the middle of the bulk operation. 
here is my implementation. 

```python

T = TypeVar("T")


@asynccontextmanager
async def acollect(
    coros: Iterable[Awaitable[T]],
    limit: Optional[CapacityLimiter] = None,
    timeout: int = 30,
) -> AsyncIterator[AsyncIterator[T]]:
    async with create_task_group() as tg:
        sender, receiver = create_memory_object_stream[T]()
        async with sender:
            for c in coros:
                tg.start_soon(_acollect_pipe, c, limit, sender.clone(), timeout)
        async with receiver:
            yield receiver


async def _acollect_pipe(
    coro: Awaitable[T],
    limit: Optional[CapacityLimiter],
    sender: MemoryObjectSendStream[T],
    timeout: int,
) -> None:
    async with AsyncExitStack() as stack:
        if limit is not None:
            await stack.enter_async_context(limit)
        await stack.enter_async_context(sender)
        try:
            with anyio.fail_after(timeout):
                value = await coro
            await sender.send(value)
        except Exception as e:
            # Send the exception instead of the value
            await sender.send(e)


async def info_hashes_to_torrent_metadata(
    info_hashes: list[str], trackers: list[str]
) -> list[dict]:
    magnets = [
        Magnet(xt=info_hash, tr=trackers or TRACKERS) for info_hash in info_hashes
    ]
    torrents_data = []

    demagnetizer = Demagnetizer()
    async with acollect(
        [demagnetizer.demagnetize(magnet) for magnet in magnets], timeout=60
    ) as async_iterator:
        async for torrent_result in async_iterator:
            try:
                if isinstance(torrent_result, Exception):
                    pass
                else:
                    torrents_data.append(extract_torrent_metadata(torrent_result))
            except Exception as e:
                logging.error(f"Error processing torrent: {e}")

    return torrents_data

```

**Comment by mhdzumair** [comment]
You can improve the code implementation.

**Comment by jwodder** [comment]
@mhdzumair I don't expect this project to expose a dedicated library API any time soon.  Does your code do what you want?  It looks like it does, in which case, you don't seem to need much from me right now.

**Comment by mhdzumair** [comment]
no worries.
